*&---------------------------------------------------------------------*
*& Include          ZTESTALV_18_001_TOP
*&---------------------------------------------------------------------*
TYPE-POOLS: COL.
TABLES: SCARR.

TYPES: BEGIN OF GTY_SCARR.

    INCLUDE TYPE SCARR.
    TYPES: COLOR(4).
    TYPES: IT_COLFIELDS TYPE LVC_T_SCOL.

TYPES: END OF GTY_SCARR.

DATA GS_COLFIELD TYPE LINE OF LVC_T_SCOL.

"----SORT-----
DATA: GT_SORT TYPE LVC_T_SORT,
      GS_SORT TYPE LVC_S_SORT.

"-------------


DATA GT_SCARR TYPE TABLE OF GTY_SCARR.
DATA GS_SCARR TYPE GTY_SCARR.
DATA GS_COLFIELD1 LIKE LINE OF GS_SCARR-IT_COLFIELDS.

DATA GT_SPFLI TYPE TABLE OF SPFLI.
DATA GT_ITAB TYPE TABLE OF SCARR.
DATA GT_ITAB2 LIKE TABLE OF GS_SCARR.

DATA OK_CODE TYPE SY-UCOMM.

DATA: GO_CONTAINER TYPE REF TO CL_GUI_CUSTOM_CONTAINER,
      GO_ALV_GRID  TYPE REF TO CL_GUI_ALV_GRID.


DATA: GS_VARIANT TYPE DISVARIANT,
      GV_SAVE    TYPE C LENGTH 1.

DATA: GS_LAYOUT TYPE LVC_S_LAYO.



SELECT-OPTIONS: SO_CAR FOR GS_SCARR-CARRID,
                SO_CAR2 FOR SCARR-CARRID.

PARAMETERS: PA_VARI TYPE DISVARIANT-VARIANT.
